version: "3"

services:
  postgres:
    image: postgres:13-alpine
    networks:
      - app-network
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'

  microservice:
    image: meu-microservice
    build:
      context: .
    networks:
      - app-network
    ports:
      - "5000:5000"
    depends_on:
      - postgres
networks:
  app-network:
    driver: bridge